services:

    mysql:
        image: mysql:8
        container_name: cadeau-mysql
        ports:
            - "3307:3307"
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: db_cadeau
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_password
        volumes:
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - cadeau-net

    # Ce connecter à la db du docker 
    # docker exec -it idConteneur bash
    # mysql -u db_user -pdb_password db_cadeau

    web:
        build:
            context: .
        ports:
            - "8000:8000"
        command: ["symfony", "server:start"]
        depends_on:
            - mysql
        networks:
            - cadeau-net

networks:
    cadeau-net:
        driver: bridge

    