name: Symfony CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Install Symfony Runtime
      run: composer require symfony/runtime

    - name: Create composer.json file if not exists
      run: |
        if [ ! -f composer.json ]; then
          echo '{"require": {"symfony/runtime": "^5.0"}}' > composer.json
        fi

    - name: Verify composer.json
      run: cat composer.json

    - name: Install PHP_CodeSniffer
      run: composer require --dev squizlabs/php_codesniffer

    - name: Lint PHP files
      run: vendor/bin/phpcs --standard=PSR2 src

    - name: Analyze PHP code with PHPStan
      run: vendor/bin/phpstan analyze

  tests:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Verify security of dependencies
      run: composer audit

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit

    - name: Run functional tests with Behat
      run: vendor/bin/behat

    - name: Generate code coverage report
      run: vendor/bin/phpunit --coverage-text


  # Si Docker est utilisé et fonctionne correctement
  # docker:
  #   runs-on: ubuntu-latest

  #   needs: tests

  #   steps:
  #   - name: Check out the repository
  #     uses: actions/checkout@v2
    # - name: Build and push Docker image
    #   run: |
    #     docker-compose build
    #     docker-compose push
    # - name: Verify Docker image security
    #   run: docker scan image-name
    # - name: Create database and run migrations
    #   run: docker-compose up -d --build && docker-compose exec -T web php bin/console doctrine:migrations:migrate --no-interaction 
