name: Symfony CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist
      
    - name: Install Symfony Runtime
      run: composer require symfony/runtime --no-plugins

    - name: Verify composer.json
      run: cat composer.json

  tests:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Verify security of dependencies
      run: composer validate --no-check-publish && composer normalize --dry-run && composer update --dry-run && composer outdated && composer outdated --direct && composer audit

    - name: Check code quality
      run: |
        composer require --dev friendsofphp/php-cs-fixer
        php vendor/bin/php-cs-fixer fix --dry-run --diff --diff-format=udiff


  # Si Docker est utilisé et fonctionne correctement
  # docker:
  #   runs-on: ubuntu-latest

  #   needs: tests

  #   steps:
  #   - name: Check out the repository
  #     uses: actions/checkout@v2
    # - name: Build and push Docker image
    #   run: |
    #     docker-compose build
    #     docker-compose push
    # - name: Verify Docker image security
    #   run: docker scan image-name
    # - name: Create database and run migrations
    #   run: docker-compose up -d --build && docker-compose exec -T web php bin/console doctrine:migrations:migrate --no-interaction 
