name: Symfony CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Create database
      run: php bin/console doctrine:database:create --env=test

    - name: Run database migrations
      run: php bin/console doctrine:migrations:migrate --env=test --no-interaction

    # - name: Load fixtures
    #   run: php bin/console doctrine:fixtures:load --env=test --no-interaction

    # - name: Run tests
    #   run: php bin/phpunit

    - name: Check code quality
      run: |
        composer require --dev friendsofphp/php-cs-fixer
        vendor/bin/php-cs-fixer fix --dry-run --diff --diff-format=udiff
